### ISSUE TITLE
Enable local testing

### ISSUE THREAD

**Issue by tylerpotts** [Quansight/qhub-cloud#135]

**Comment by tylerpotts** [comment]
- using minikube

**Comment by tylerpotts** [comment]
@brl0 Could you post your progress and limitations here?

**Comment by laisbsc** [comment]
I believe this issue was picked up by @aktech.

Is it still relevant? Is there a PR to be linked here?

**Comment by brl0** [comment]
This was working using these PRs:
https://github.com/Quansight/qhub-cloud/pull/208
https://github.com/Quansight/qhub-terraform-modules/pull/27

Let me know what I can do to help move this forward.

**Comment by costrouc** [comment]
Closing as we now have local testing in the dev branch.
