### ISSUE TITLE
Error to deploy cluster with dask_gateway

### ISSUE THREAD

**Issue by jkellndorfer** [Quansight/qhub-cloud#141]
Here is a screenshot of the error message I get when use default_gateway. It worked the first time around, altough some version mismatch didn't make the cluster usable, so I tried to restart when this error happended.

![image](https://user-images.githubusercontent.com/10451217/97037003-ae341c00-1536-11eb-8718-d08d92f2cae0.png)

This is with the default environment which is in the config file:

> environments:
>   "environment-default.yaml":
>     name: default
>     channels:
>       - conda-forge
>       - defaults
>     dependencies:
>       - python=3.7
>       - ipykernel
>       - ipywidgets
>       - dask==2.14.0
>       - distributed==2.14.0
>       - dask-gateway=0.6.1
>       - flask
>       - numpy
>       - numba
>       - pandas
>

**Comment by brl0** [comment]
@jkellndorfer, A possible work-around that might help is to scale the `gateway-dask-gateway` down and then back up as follows:
```
kubectl scale --replicas=0 deployment gateway-dask-gateway -n dev
kubectl scale --replicas=1 deployment gateway-dask-gateway -n dev
```

**Comment by jkellndorfer** [comment]
@brl0 thanks for the tip. It didn't work because apparently the admin permissions seem to think I am user root. But after a complete redeploy of the jupyterhub, the commands seem to work again. I'll keep folks updated in case I run into the issue again.

**Comment by jkellndorfer** [comment]
@brl0. I can install kubectl, but might you know how to connect to the dask-gateway cluster created by qhub?

**Comment by laisbsc** [comment]
Did this solve your issue @jkellndorfer? If so I might close this issue and add this info to the docs.

Let me know what worked for you :)

And thanks a million again for the FAQ repo. I would also love to help write some tutorials for your awesome notebooks, if that is something you would be interested on.

Chat soon!

**Comment by laisbsc** [comment]
I will go ahead and close this issue for now since I think this problem has been resolved.

Thanks again and please feel free to reopen in case you need further assistance.
Thank ya :)
