### ISSUE TITLE
Document Oauth providers and set up with QHub

### ISSUE THREAD

**Issue by prasunanand** [Quansight/qhub-cloud#158]
JupyterHub's OAuthenticator currently supports the following popular services:  https://jupyterhub.readthedocs.io/en/stable/reference/authenticators.html

- [ ] Auth0
- [ ] Bitbucket
- [ ] CILogon
- [ ] GitHub
- [ ] GitLab
- [ ] Globus
- [ ] Google
- [ ] MediaWiki
- [ ] Okpy
- [ ] OpenShift

**Comment by laisbsc** [comment]
Does this mean we will have a different set of CLI commands and *modus operandi* for each of those? Can you tell me which ones are the most used (or essential) for an initial version of the docs?

Just so I can break this issue into a few.

Thanks @prasunanand! :)

**Comment by laisbsc** [comment]
Due to inactivity and lack of contextual description, I will go ahead and close this issue. 
If anything related to this comes back to life, feel free to reopen the issue and tag me on it.
