### ISSUE TITLE
Add testing to qhub

### ISSUE THREAD

**Issue by tylerpotts** [Quansight/qhub-cloud#166]
- qhub can test deployment on the 3 supported cloud providers
- qhub can spin up dask workers and output the time to spin up as well as any errors

- [x] create a `qhub destroy` command
- `qhub destroy` will automatically retry the destroy
- if it fails destroys anything with a unique tag
- have warning messages and require user input if it will destroy data

**Comment by laisbsc** [comment]
@tylerpotts Is it okay if we make this into two different tickets?

One for testing, which will link Amit's PR for the testing rep,o and another one for the creation of the `qhub detroy` command.

Also, is the `qhub destroy` command linked to issue #227 and #99?

**Comment by tylerpotts** [comment]
@laisbsc QHub destroy was actually added in a community PR in https://github.com/Quansight/qhub/pull/219. 

I would say it's partially related, but those two issues are different. 

#227 is about saving money by not having a running k8s cluster when the compute isn't being used which would involve using the `qhub destroy` command.

#99 Is about having a backup strategy for QHub for data

**Comment by costrouc** [comment]
Closing as too broad. @tylerpotts is creating an epic
