### ISSUE TITLE
How to pass environment variables to Dask Gateway workers?

### ISSUE THREAD

**Issue by rsignell-usgs** [Quansight/qhub-cloud#167]
Related to #162, I'm trying to figure out how to give the Dask Gateway workers the credentials to be able to access requester pays buckets. 

@scottyhq has a nice example notebook showing [how he passes environment variables to Dask Gateway workers](https://github.com/pangeo-data/cog-best-practices/blob/main/3-dask-gatewaycluster.ipynb) using an AWS Pangeo deployment. 

The Gateway options look like this: 
![2020-11-09_11-37-15](https://user-images.githubusercontent.com/1872600/98569830-bf905e80-2280-11eb-920e-c36b2c6fb339.png)

and basically he constructs a dict to pass to the `environment` option. 

This fails on qhub because the gateway options look quite different, and environment expects a string. 

How do we pass environment variables to the Dask Gateway workers?

**Comment by jkellndorfer** [comment]
Found a workaround with @rsignell-usgs with hint from [https://github.com/pangeo-data/cog-best-practices/blob/main/3-dask-gatewaycluster.ipynb](https://github.com/pangeo-data/cog-best-practices/blob/main/3-dask-gatewaycluster.ipynb)
Assuming we have a `client` running, one can deploy environment variables via `client.run` and a custom function.
```
def set_env(key,value):
    import os
    os.environ[key]=value

# Example to set `MYENV=MYVALUE` on all workers
client.run(set_env,MYENV,MYVALUE)
```

**Comment by laisbsc** [comment]
This looks pretty cool. I will make a note to add these to the documentation. Thanks a million for recording it. 🥇 

And since the issue is solved, I will go ahead and close it for now. Feel free to reopen in case something pops out, though.

**Comment by tylerpotts** [comment]
reopening, as an accidentally merged PR closed it

**Comment by rsignell-usgs** [comment]
closing in favor of the discussion here:  https://github.com/Quansight/qhub-cloud/discussions/331
