### ISSUE TITLE
ExternalDNS

### ISSUE THREAD

**Issue by brl0** [Quansight/qhub-cloud#206]
[ExternalDNS](https://github.com/kubernetes-sigs/external-dns) looks like a possible way to add support for lots of DNS providers.  Helm chart is [here](https://github.com/bitnami/charts/tree/master/bitnami/external-dns/).

**Comment by laisbsc** [comment]
@costrouc and @tylerpotts I believe this ticket will no longer be relevant once we remove Helm from QHub, right?

I will add it to the tech-discussion stack for discussion since I believe we should add more details to the issue.

**Comment by laisbsc** [comment]
Under technical discussion the team decided this issue is out-of-scope.
