### ISSUE TITLE
On premise deployment of QHub

### ISSUE THREAD

**Issue by costrouc** [Quansight/qhub-cloud#216]
This is an issue to track progress on making QHub deployable on existing kubernetes clusters and on-prem deployments.

**Comment by laisbsc** [comment]
@costrouc I am a little bit confused about this ticket.

Since this is on-prem shouldn't it be part of [QHub-HPC](https://github.com/Quansight/qhub-hpc)? Or is the Epic describing two different things?

Can you elaborate, please ❔

**Comment by Adam-D-Lewis** [comment]
In the on-prem hpc faq, it says 
>We have eventual plans for supporting existing on-prem kubernetes deployments in issue #216. HPC still has many advantages over kubernetes:
>  - simplicity as it following a more traditional linux and systemd making it easier to diagnose errors
>  - can deployed to take advantage of pre-provisioned existing infrastructure
>  - TODO still possible to support containerized workflows
>  - can fully take advantage of HPC infrastructure in on-prem datacenter

**Comment by costrouc** [comment]
Resolved by PR https://github.com/Quansight/qhub-cloud/pull/287
