### ISSUE TITLE
Demo with QHub and Bodo

### ISSUE THREAD

**Issue by laisbsc** [Quansight/qhub-cloud#235]
Create a demo using Bodo and HPC:
* Seems like QHub is not in the position to demo Bodo at the moment;
* Use HPC instead for now.
* Ideally, multimode for now. "The spirit of Bodo is lost if we don't do multinode".

**Comment by laisbsc** [comment]
@costrouc to talk to @dharhas and nail down requirements.

**Comment by tylerpotts** [comment]
This is scheduled for this afternoon at 2pm CST: https://app.livestorm.co/openteams/qstream-bodo-and-qhub

 Closing
