### ISSUE TITLE
Github usernames with uppercase letters don't work

### ISSUE THREAD

**Issue by rsignell-usgs** [Quansight/qhub-cloud#246]
## Describe the bug
GitHub names with uppercase letters don't work.

## How can we help?
We wanted to get someone on our qhub who didn't yet have an account on GitHub, so he created one: KorySteinberg.  
I put "KorySteinberg" in the config file, but that didn't work.  I think it returned a 500 error. 

When he renamed it to "korysteinberg" and I changed the config to that it worked.

Hmmm, would it have worked if I just used the lowercase version in the config even if he didn't change his username?  I hope not, since GitHub recognizes uppercase letters in usernames, right?

**Comment by laisbsc** [comment]
Hey @rsignell-usgs, thank you for your issue (and patience).

GitHub treats usernames with a [case insensitive way](https://happygitwithr.com/github-acct.html#username-advice) so I think that only changing the username on the config file would work.

In any case, if you manage to test this please let us know what you discover!

Thanks a million 🎖️

**Comment by rsignell-usgs** [comment]
@laisbsc, okay, good to know!

**Comment by laisbsc** [comment]
My pleasure!

I will go ahead and close this issue for now but please, feel free to reopen it in case you find something new regarding QHub and GitHub's case-sensitivity.

Thanks a million.
