### ISSUE TITLE
DO Deployment broken: Error: Unsupported argument load_config_file       = false

### ISSUE THREAD

**Issue by aktech** [Quansight/qhub-cloud#261]
## Describe the bug
I tried deploying qhub on DigitalOcean, it seems the terraform is broken somehow, I get the following error on running the deploy command:

```
Error: Unsupported argument

  on kubernetes.tf line 2, in provider "kubernetes":
   2:   load_config_file       = false
```

Command to reproduce:

```
qhub deploy -c qhub-config.yaml --dns-provider cloudflare --dns-auto-provision --disable-prompt
```

**Comment by aktech** [comment]
Here is the root cause:

https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/guides/v2-upgrade-guide#changes-to-kubernetes-credentials-supplied-in-the-provider-block

> The load_config_file attribute has been removed.

**Comment by aktech** [comment]
`load_balancer_ingress` has also changed: https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/guides/v2-upgrade-guide#changes-to-the-load_balancers_ingress-block-on-service-and-ingress

**Comment by tylerpotts** [comment]
@aktech Just got reported from @bl0 that this is also happening on GCP

**Comment by aktech** [comment]
@tylerpotts  Yes, this will happen on all cloud provider, I have a fix, will create a PR in a few minutes.
