### ISSUE TITLE
Github action `Terraform validate` failing: An argument named "load_config_file" is not expected here.

### ISSUE THREAD

**Issue by rsignell-usgs** [Quansight/qhub-cloud#264]
I tried a minor tweak to my config today (just added a single package from conda-forge to one of my environments) and the github action failed on "Terraform validate" with "An argument named "load_config_file" is not expected here."   Here's the full traceback:

```python-traceback
Run hashicorp/terraform-github-actions@master
/usr/bin/docker run --name c2e63a7bbb0d4994b867bdbc75362b23_4c8736 --label 442333 --workdir /github/workspace --rm -e GITHUB_TOKEN -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY -e AWS_DEFAULT_REGION -e INPUT_TF_ACTIONS_VERSION -e INPUT_TF_ACTIONS_SUBCOMMAND -e INPUT_TF_ACTIONS_WORKING_DIR -e INPUT_TF_ACTIONS_COMMENT -e INPUT_TF_ACTIONS_CLI_CREDENTIALS_HOSTNAME -e INPUT_TF_ACTIONS_CLI_CREDENTIALS_TOKEN -e INPUT_TF_ACTIONS_FMT_WRITE -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/qhub/qhub":"/github/workspace" 442333:c2e63a7bbb0d4994b867bdbc75362b23
Downloading Terraform v0.13.4
Successfully downloaded Terraform v0.13.4
Unzipping Terraform v0.13.4
Successfully unzipped Terraform v0.13.4
validate: info: validating Terraform configuration in infrastructure
validate: error: failed to validate Terraform configuration in infrastructure

Warning: Interpolation-only expressions are deprecated

  on .terraform/modules/qhub/modules/kubernetes/services/meta/qhub/main.tf line 16, in module "kubernetes-jupyterhub":
  16:           "${var.general-node-group.key}" = var.general-node-group.value

Terraform 0.11 and earlier required all non-constant expressions to be
provided via interpolation syntax, but this pattern is now deprecated. To
silence this warning, remove the "${ sequence from the start and the }"
sequence from the end of this expression, leaving just the inner expression.

Template interpolation syntax is still used to construct strings from
expressions when the template includes multiple interpolation sequences or a
mixture of literal strings and interpolations. This deprecation applies only
to templates that consist entirely of a single interpolation sequence.

(and 3 more similar warnings elsewhere)


Error: Unsupported argument

  on kubernetes.tf line 2, in provider "kubernetes":
   2:   load_config_file       = false

An argument named "load_config_file" is not expected here.

**Comment by rsignell-usgs** [comment]
ping @costrouc

**Comment by laisbsc** [comment]
Hey @rsignell-usgs,
thanks for reporting this. This is a bug we found and has been fixed on this [PR](https://github.com/Quansight/qhub-cloud/pull/262). We are currently adjusting a few more details to launch a new release with that fix and some other changes.

Chat soon.

**Comment by rsignell-usgs** [comment]
@laisbsc are there or will there be instructions on how to upgrade an existing Qhub deployment to the new release?

**Comment by laisbsc** [comment]
Hey @rsignell-usgs,

> @laisbsc are there or will there be instructions on how to upgrade an existing QHub deployment to the new release?

Currently, there are no instructions detailing how to upgrade deployment versions. Although, the backend team said that is QHub's version is not pinned to the config file, CI will auto upgrade to the latest version of QHub and you don't need to worry about anything else.
Hence, if you wish to auto upgrade your version, simply check that the `qhub-config.yaml` does not have a pinned version and all should be good.

And we are aware this info should also be added somewhere, so the `release notes` will contain more details on migration guidelines and breaking changes in general.

Let me know if we can help with anything else :)

Chat soon!

**Comment by rsignell-usgs** [comment]
@laisbsc , when you say 
> simply check that the `qhub-config.yaml` does not have a pinned version and all should be good
does that mean I should change:
 
```
default_images:
  jupyterhub: "quansight/qhub-jupyterhub:1abd4efb8428a9d851b18e89b6f6e5ef94854334"
  jupyterlab: "quansight/qhub-jupyterlab:1abd4efb8428a9d851b18e89b6f6e5ef94854334"
  dask_worker: "quansight/qhub-dask-worker:1abd4efb8428a9d851b18e89b6f6e5ef94854334"
```
to 
```
  jupyterhub: "quansight/qhub-jupyterhub"
  jupyterlab: "quansight/qhub-jupyterlab"
  dask_worker: "quansight/qhub-dask-worker"
```
Or @jkellndorfer, perhaps you see what we need to do?

**Comment by costrouc** [comment]
@rsignell-usgs are you trying to change the docker image that is used for jupyterlab? A common use case for this is adding extensions and apt packages. If you need to modify the conda environment I'd use the environments key. Is this what you are asking?

**Comment by rsignell-usgs** [comment]
@costrouc , I'm just trying to get the github action not to fail with on terraform validate.

**Comment by laisbsc** [comment]
Alright, @rsignell-usgs. I'm sorry for the delay.

Can we try and update QHub to version 0.2.0 on your virtual env and run it again to see if it fixes the issue?
The terraform validate error was a bug that it has been fixed on the new version.

**Comment by laisbsc** [comment]
and @costrouc what I believe @rsignell-usgs is asking is where in the config file is the version of QHub is pinned (if pinned at all). 

Simply put: **how to upgrade projects to the latest version of QHub, making sure they will work.**

**Comment by costrouc** [comment]
@rsignell-usgs right now you need to change the qhub version being used. We don't have an easy way to trigger this at the moment. Modify `.github/workflows/qhub-ops.yaml`

```
...
       pip install qhub==0.1.21
...
```

To the newest version qhub==0.2.0 and trigger the workflow.

**Comment by laisbsc** [comment]
> @rsignell-usgs right now you need to change the qhub version being used. We don't have an easy way to trigger this at the moment. Modify `.github/workflows/qhub-ops.yaml`
> 
> ```
> ...
>        pip install qhub==0.1.21
> ...
> ```
> 
> To the newest version qhub==0.2.0 and trigger the workflow.

So, it is not on the `qhub-config.yaml` with the pinned version but the `.github/workflows/qhub-ops.yaml`. Thank you! TIL

**Comment by rsignell-usgs** [comment]
I made the mod, and I see that qhub=0.2.0 installed okay, but the next step fails:
```
Run qhub render -c qhub-config.yaml -o ./ -f
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.6/x64/bin/qhub", line 8, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/qhub/__main__.py", line 7, in main
    cli(sys.argv[1:])
  File "/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/qhub/cli/__init__.py", line 40, in cli
    args.func(args)
  File "/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/qhub/cli/render.py", line 29, in handle_render
    verify(config)
  File "/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/qhub/schema.py", line 207, in verify
    Main(**config)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Main
terraform_version
  field required (type=value_error.missing)
Error: Process completed with exit code 1.
```

**Comment by tylerpotts** [comment]
@rsignell-usgs Just became aware of this. Reading through it now

**Comment by tylerpotts** [comment]
@rsignell-usgs We added a terraform flag in the `qhub-config.yaml` to prevent unexpected failures when terraform updates. This wasn't documented, and I'm sorry it's causing so much trouble.

The solution is to run: `terraform --version` and then take your current version and add it to `qhub-config.yaml` like below:
```
project_name: example-proj
provider: gcp
ci_cd: github-actions
domain: qhub.dev
terraform_version: 0.14.5
```

**Comment by rsignell-usgs** [comment]
@tylerpotts , okay, making progress!   
 On to the next problem:  the "QHub Build Dockerfile (jupyterhub) " action is failing with:
```
Step 7/9 : RUN cd /opt &&     curl -L "https://github.com/${THEME_OWNER}/${THEME_REPO}/archive/${THEME_REV}.tar.gz" -o theme.tar.gz     && tar -xf theme.tar.gz     && mkdir -p /usr/local/share/jupyterhub/custom_templates     && mkdir -p /usr/local/share/jupyterhub/static/extra-assets     && cp -r "/opt/${THEME_REPO}-${THEME_REV}/templates/." /usr/local/share/jupyterhub/custom_templates/     && cp -r "/opt/${THEME_REPO}-${THEME_REV}/extra-assets/." /usr/local/share/jupyterhub/static/extra-assets/     && rm -rf "/opt/theme.tar.gz" "/opt/${THEME_REPO}-${THEME_REV}"
 ---> Running in 216de391d335
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   173  100   173    0     0   1696      0 --:--:-- --:--:-- --:--:--  1696

100  112k    0  112k    0     0   426k      0 --:--:-- --:--:-- --:--:--  426k
Removing intermediate container 216de391d335
 ---> a5978b175303
Step 8/9 : WORKDIR /srv/jupyterhub
 ---> Running in 1ab6854b9f7a
Removing intermediate container 1ab6854b9f7a
 ---> 2551df4e5438
Step 9/9 : USER ${NB_USER}
 ---> Running in 6df06aeec394
Removing intermediate container 6df06aeec394
 ---> de9775e18b7f
Successfully built de9775e18b7f
Successfully tagged ***.dkr.ecr.***.amazonaws.com/esipfed-qhub-jupyterhub:f3c9e5c39485dd0dcffd85d5333c9d95f4eef7a4
The push refers to repository [***.dkr.ecr.***.amazonaws.com/esipfed-qhub-jupyterhub]
189ffcf0080a: Preparing
ee3175c0891e: Preparing
dfd14caa8353: Preparing
0fd5d12fc47f: Preparing
0387e5ac20e6: Preparing
5de529f1e88b: Preparing
258d5cea5895: Preparing
ac4fc6c63427: Preparing
16542a8fc3be: Preparing
6597da2e2e52: Preparing
977183d4e999: Preparing
c8be1b8f4d60: Preparing
5de529f1e88b: Waiting
258d5cea5895: Waiting
ac4fc6c63427: Waiting
16542a8fc3be: Waiting
6597da2e2e52: Waiting
977183d4e999: Waiting
c8be1b8f4d60: Waiting
name unknown: The repository with name 'esipfed-qhub-jupyterhub' does not exist in the registry with id '***'
Error: Process completed with exit code 1.
```

**Comment by rsignell-usgs** [comment]
@tylerpotts , I invited you as an admin at our private repo: https://github.com/ESIPFed/qhub

**Comment by dharhas** [comment]
@rsignell-usgs when is your presentation. I assume you are still blocked?

**Comment by rsignell-usgs** [comment]
We were thinking to use this in Dave Neufeld's presentation, as it would be nice to show the ESIP qhub in action.

**Comment by laisbsc** [comment]
Since the new version(s) have been released and the demo has been executed, I will go ahead and close this issue.
