### ISSUE TITLE
Terraform 0.13.6 breaks qhub

### ISSUE THREAD

**Issue by tylerpotts** [Quansight/qhub-cloud#278]
QHub code allows minor releases of terraform 'v0.13`, but `v0.13.6` results in an error with the s3 backend. Reverting to `v0.13.5` caused the problem to go away.

I propose we only support a single version of terraform at a time. The latest confirmed working version of terraform is `v0.13.5`

**Comment by laisbsc** [comment]
this issue was fixed by PR #280
