### ISSUE TITLE
Changes to the readme in a qhub repo don't persist

### ISSUE THREAD

**Issue by kcpevey** [Quansight/qhub-cloud#284]
## Describe the bug
Any changes to the readme in my qhub repo are lost/reverted when a redeploy is triggered. 

## How can we help?
Help us help you.
* What are you trying to achieve?
I need to edit the readme in my qhub repo
* How can we reproduce the problem?
edit the readme file. commit/merge. Then redeploy qhub.
* What is the expected behaviour?
I would expect the changes to the readme to persist.
* And what is currently happening?
The changes to the readme that I commited are lost and the readme looks like it did before I made changes.
* Any error messages?
nope

## Your environment
This is all on the github repo

**Comment by tylerpotts** [comment]
I think we should delete the README from the templates. All of the documentation is in qhub.dev, and this will allow users the flexibility to write their own README files specific to their team

**Comment by tylerpotts** [comment]
Removing it from templates will also prevent the existing readme from getting overwritten when `qhub render -c qhub-config.yaml ./` is run via github actions

**Comment by kcpevey** [comment]
Thanks!
