### ISSUE TITLE
Terraform throws an error if prefect_token variable not set

### ISSUE THREAD

**Issue by tylerpotts** [Quansight/qhub-cloud#286]
## Describe the bug
Terraform throws an error if prefect_token variable not set

**Comment by aktech** [comment]
Can you elaborate, that is an expected behaviour, its is set in CI for automated deployment and for local you have to set TF_VAR_prefect_token environment variable or pass it as CLI using `-var` ?

**Comment by aktech** [comment]
Ah, I see what you mean, I just saw the check for if prefect set is incorrect:

https://github.com/Quansight/qhub-cloud/blob/74fc27b80529c18b2516867b04fc0c840beb1ef8/qhub/template/%7B%7B%20cookiecutter.repo_directory%20%7D%7D/infrastructure/variables.tf#L89

It should be rather: `{% if cookiecutter.prefect is true -%}`, I'll create a PR in a sec.
