### ISSUE TITLE
Remove the need for users to manually install Terraform

### ISSUE THREAD

**Issue by costrouc** [Quansight/qhub-cloud#289]
## Problem
We run into a lot of issues with terraform versions. Some of these include the fact that people download the wrong Terraform version - deploying with a newer version makes the existing files backward-incompatible, breaking things. Also, manually installing Terraform brings a significant overhead to the already complex initial QHub setup.

## Proposed Solution
To solve this, we would like to add the Terraform binary file for the current compatible version (at this point v0.13.5) to the GitHub files so when the command `qhub deploy` is run, those files would be used to deploy the necessary resources instead of the user manually installing Terraform.

### Possible downsides
* the need to use Terraform commands when debugging QHub.
* the need to manually add the path to the binary file on the QHub directory upon initial configuration.

* What will be the implications of running  in QHub directories?

### Steps to resolve this issue:
- [ ] Add Terraform binary v0.13.5 to GitHub repository.
- [ ] prompt user  (on CLI?) to download Terraform install file and add the path to QHub install.
- Add the step to the documentation:
- [ ] how to add the downloaded binary to the setup workflow
- [ ] debug QHub - what happens if the user ever needs to manually run terraform commands (i.e., `terraform destroy`)?

**Comment by laisbsc** [comment]
For now, add the step-by-step Terraform install on the install docs.

**Comment by danlester** [comment]
It should be possible to always run terraform inside GitHub actions, at least in the normal course of things going as planned.

The `qhub init` step would be done on the user's machine, but then the initial commit should trigger the terraform run inside GA.

That way, the user should not need to have a local terraform installation at all.

Downside perhaps is that any errors on initial deploy might be 'hidden' a little bit in GA logs, unless we connect directly to GA actions to print the logs on the console.

**Comment by tylerpotts** [comment]
Per @costrouc:

- Use currently supported terraform version
- We could install the binary to a temporary file path `/tmp/<...>`
- `qhub deploy` would check if supported terraform version is installed, download into os specific `/tmp` directory if not
