### ISSUE TITLE
Discussion around dev/release branches

### ISSUE THREAD

**Issue by tylerpotts** [Quansight/qhub-cloud#295]
Potential options for having a dev branch

- Github flow
- Git flow
- Master is always release branch, separate dev branch

**Comment by tylerpotts** [comment]
https://i2.wp.com/lanziani.com/slides/gitflow/images/gitflow_1.png

**Comment by laisbsc** [comment]
I believe everything regarding this issue was nicely captured at #296. I've added the image from the latest comment to the HackMD that contains the draft for the standard development workflow for QHub.

On this note, I will go ahead and close this issue.
