### ISSUE TITLE
Node type assignment

### ISSUE THREAD

**Issue by brl0** [Quansight/qhub-cloud#321]
Pods for some core services have migrated over to high-memory nodes, which have a much higher cost that the general nodes.  I tried killing the pod hoping it would restart on a different node, but usually it just restarts on the same node.
I was able to temporarily correct the issue with the following command:
`kubectl drain <pod> --ignore-daemonsets`
These services need Node-Selectors to ensure proper assignment to general nodes:
- conda-store
- nfs server
- dask-gateway

**Comment by brl0** [comment]
Fixes for conda-store and nfs-server are available in #323 and https://github.com/Quansight/qhub-terraform-modules/pull/39
Fix for dask-gateway is available in https://github.com/Quansight/qhub-terraform-modules/pull/37

**Comment by brl0** [comment]
This happens daily due to prefect jobs spinning up resources and causes increased costs of the cluster at rest since an extra high-memory node stays running until I run the command above.

In addition to the suggested fixes above, I think the proper fix is to set a taint on the nodes to prevent other workloads from being scheduled on them, as seen in 2i2c's terraform setup [here](https://github.com/2i2c-org/pilot-hubs/blob/master/terraform/main.tf#L141-L154).

@dharhas, any chance we can get this added to the next release?

**Comment by dharhas** [comment]
Added to the upcoming release milestone. @brl0 if you feel confident in adding another PR to set the taints go for it.

**Comment by costrouc** [comment]
@brl0 closing this issue. Let us know if merging that PR and the new release does not fix the issues.
