### ISSUE TITLE
Define tasks to upgrade dask gateway

### ISSUE THREAD

**Issue by tylerpotts** [Quansight/qhub-cloud#322]
There is an open PR #315 to upgrade dask, but it might not work

There is a current issue outlining how to get rid of helm https://github.com/Quansight/qhub-cloud/issues/224

@costrouc You have the most info here, would you mind answering these questions? 

- [ ] Do we need to get rid of helm to upgrade dask gateway? If so, why?
- [ ] What are the current details/pain points for upgrading dask?

**Comment by costrouc** [comment]
It is not required to remove Helm. So current PRs that brian submitted should be enough.

**Comment by tylerpotts** [comment]
Closing since these questions are no longer relevant
