### ISSUE TITLE
Adding Azure support

### ISSUE THREAD

**Issue by costrouc** [Quansight/qhub-cloud#34]
Does not look too tricky:
 - private registries
 - shared filesystem
 - kubernetes cluster

**Comment by balast** [comment]
I'm interested in working on this,

**Comment by costrouc** [comment]
@balast so for getting started all the initial work you'll need to do will be contributing to https://github.com/Quansight/qhub-terraform-modules/tree/master/modules. You will need to create a new directory `azure`. I would recommend starting as simple as possible.

1. terraform state storage https://docs.microsoft.com/en-us/azure/developer/terraform/store-state-in-azure-storage
2. kubernetes related requirements
 - kubernetes cluster https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster
 - kubernetes node groups https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster_node_pool
    - 3 node pool (general, user, worker)
 - container registry https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/container_registry
 
For the initial deployment vpn/subnets etc. can be ignored. We'll include this in future PR. I have a meeting scheduled with Ashley to create a cloud account for testing.

https://github.com/Quansight/qhub-terraform-modules/tree/master/modules/gcp is a good model for what you will need to create (only kubernetes, terraform-state, and registry) modules need to be created.

**Comment by rsignell-usgs** [comment]
ping @TomAugsberger, just FYI

**Comment by TomAugspurger** [comment]
Thanks for the ping Rich.

I have some terraform scripts for setting up AKS resources with daskhub (resource group, virtual network / subnet, aks cluster, various node pools (core, user, worker), container registry, and various other random things). @balast let me know if any of that would be helpful and I can throw it in a gist.

**Comment by TomAugspurger** [comment]
Just in case it's helpful I've put an example in https://gist.github.com/3a77bb89f75f07667107f83cad534e80. That's a cleaned up version of a more complex deployment (AzureAD for auth, GPU node pools, a few other things...) but hopefully it's mostly correct.

**Comment by rsignell-usgs** [comment]
Thanks @TomAugspurger !   I've got a few colleagues who would like to try this out with their Azure credits!

**Comment by balast** [comment]
That looks great, thanks @TomAugspurger.  I'll take a look at it as I work on this.

**Comment by costrouc** [comment]
Steps to complete this. 

For myself I need to write docs on how to contribute new cloud providers to qhub.

1. need to at a minimum add:
   - [X] managed kubernetes with connection information https://github.com/Quansight/qhub-terraform-modules/tree/master/modules/digitalocean/kubernetes
   - [ ] terraform remote state https://github.com/Quansight/qhub-terraform-modules/tree/master/modules/digitalocean/terraform-state it looks like terraform docs recommend using https://www.terraform.io/docs/language/settings/backends/azurerm.html
   - [ ] container registry https://github.com/Quansight/qhub-terraform-modules/tree/master/modules/digitalocean/registry

The `variable.tf` for each module should try to follow the already established variables as much as possible to minimize the amount of cookiecutter provider specific logic

Now once we have added the qhub-terraform-modules for the given cloud provider

2. create a file similar to https://github.com/Quansight/qhub-cloud/blob/main/qhub/template/%7B%7B%20cookiecutter.repo_directory%20%7D%7D/infrastructure/do.tf `azure.tf`. This terraform file should provision the container registry, Kubernetes
3. Add the terraform remote state logic for azure https://github.com/Quansight/qhub-cloud/blob/main/qhub/template/%7B%7B%20cookiecutter.repo_directory%20%7D%7D/terraform-state/main.tf
4. Add the azure provider elif statement and delete the others following this terrible pattern https://github.com/Quansight/qhub-cloud/blob/main/qhub/template/hooks/post_gen_project.py#L20
5. Add to cookiecutter.json similar to https://github.com/Quansight/qhub-cloud/blob/main/qhub/template/cookiecutter.json#L15
6. Provide the Kubernetes connection logic https://github.com/Quansight/qhub-cloud/blob/main/qhub/template/%7B%7B%20cookiecutter.repo_directory%20%7D%7D/infrastructure/kubernetes.tf#L1-L5
7. Connect github-actions with the azure container registry https://github.com/Quansight/qhub-cloud/blob/main/qhub/template/%7B%7B%20cookiecutter.repo_directory%20%7D%7D/.github/workflows/image.yaml so that github actions deploy to azure (not required for now)

**Comment by costrouc** [comment]
Also create docs similar to https://github.com/Quansight/qhub-cloud/blob/main/docs/docs/qhub-do-deployment.md

**Comment by Adam-D-Lewis** [comment]
I also needed to 
- [ ] 9. update initialize.py in qhub-cloud (https://github.com/Quansight/qhub-cloud/blob/main/qhub/initialize.py)

**Comment by costrouc** [comment]
Forgot to add that the helm provider connection information needs to be updated as well. @Adam-D-Lewis and I caught this when debugging.
