### ISSUE TITLE
Integrate CDS-Dashboards into Qhub-cloud

### ISSUE THREAD

**Issue by Adam-D-Lewis** [Quansight/qhub-cloud#340]

**Comment by costrouc** [comment]
1. We need to build our own jupyterhub image https://github.com/Quansight/qhub-cloud/tree/main/qhub/template/%7B%7B%20cookiecutter.repo_directory%20%7D%7D/image
   - to include cds dashboard environment
 2. Add cds dashbaord client package to jupyterlab docker image https://github.com/Quansight/qhub-cloud/blob/main/qhub/template/%7B%7B%20cookiecutter.repo_directory%20%7D%7D/image/jupyterlab/environment.yaml


https://cdsdashboards.readthedocs.io/en/stable/chapters/setup/z2jh.html

**Comment by danlester** [comment]
There is a branch in the cdsdashboards repo incorporating 'spawner options' into the core dashboard build process. This should allow you to simplify your code, and fixes the problem with restarting the server breaking the dashboard-ness of it (launching JupyterLab instead).

https://github.com/ideonate/cdsdashboards/tree/useroptions
