### ISSUE TITLE
Update qhub to use jupyterlab 3

### ISSUE THREAD

**Issue by costrouc** [Quansight/qhub-cloud#350]
Required compatibility to move towards jupyterlab 3:
  - [X] dask-labextension >= 5.0.0
  - [X] ipywidgets >= 7.6
  - [X] pyviz_comms >= 2.0.1
  - [X] jupyterlab-videochat >= 0.5.1
  - [X] jupyterlab/toc (added by default in 3)
  - [X] ipyleaflet 0.13.5

We are ready to move towards 3.0!

**Comment by dharhas** [comment]
Is the cds dashboards integration relevant or is that more a jhub integration than a jlab one?

**Comment by costrouc** [comment]
This is more of a jhub integration and nothing to do with jlab
