### ISSUE TITLE
jupyterhub profiles not showing correctly in dev branch

### ISSUE THREAD

**Issue by brl0** [Quansight/qhub-cloud#393]
I merged the dev branch into my branch for deploying with Kubernetes in Docker (kind).
Since the update, I only see the default instance profile when I log in.
I think the issue may not be limited to my branch, and I wanted to see if anybody else is seeing this issue on the dev branch.  If not, then this issue can be closed.

**Comment by brl0** [comment]
I tested using the local testing instructions with minikube in the dev branch and was able to reproduce the issue.
The dev branch currently seems to be in a broken state.

**Comment by costrouc** [comment]
Thanks for the issue @brl0. We saw this issue a few other places as well. This PR will fix it once merged https://github.com/Quansight/qhub-cloud/pull/435. I've setup the PR to close this issue when merged.
