### ISSUE TITLE
Add link to new documentation to qhub-cloud github repo readme

### ISSUE THREAD

**Issue by Adam-D-Lewis** [Quansight/qhub-cloud#397]
Add link to https://cloud.qhub.dev/en/latest/index.html to qhub-cloud github repo readme. @laisbsc what are your thoughts on this?

**Comment by laisbsc** [comment]
I think it can be done :) Is there a special reason why you think the docs link should be added to the repo?
I have no objections, just trying to understand the motivation :)

Thanks

**Comment by laisbsc** [comment]
Cool! Sounds like a good reason to me. Thanks, will take care of it now.

**Comment by laisbsc** [comment]
Checking the README I noticed this has been solved 😅 by the line
> This repository details the QHub Cloud version.

The sentence links to [https://qhub.dev] that currently points to the latest version of the docs (`dev` branch).
