### ISSUE TITLE
Name change for QHub and Qhub OnPrem

### ISSUE THREAD

**Issue by laisbsc** [Quansight/qhub-cloud#412]
@tylerpotts pointed out that we should rename QHub Cloud and Qhub OnPrem. This ticket aims to host the discussion about the name change. This issue has high priority since it is a blocker for the documentation and the creation of the QHub landing page.

**Comment by tylerpotts** [comment]
Steps for this:
1. Merge all PRs for the next release 
2. Create PR for renaming
3. Profit
