### ISSUE TITLE
Adding support for deploying to specific namespace

### ISSUE THREAD

**Issue by costrouc** [Quansight/qhub-cloud#432]
There two related issues that will be resolved if this is implemented:
  - https://github.com/Quansight/qhub-cloud/issues/100
  - https://github.com/Quansight/qhub-cloud/issues/115

Idea is to add a `namespace` key to `qhub-config.yaml`

```yaml
project_name: asdfasdfasdf
namespace: dev
...
```

This will take advantage of the fact that we already have support for deploying resources in specific namespaces.

I think the controversial question is what to call the option: suggested names:
  - `namespace` my favorite
  - `environment`
  - `prefix`

**Comment by dharhas** [comment]
+1 for namespace.
