### ISSUE TITLE
[documentation] User Feedback on the `latest` docs

### ISSUE THREAD

**Issue by laisbsc** [Quansight/qhub-cloud#446]
We have been trying to revampQHub docs to reflect the current state of the development.

Our user @leej3 flagged some of his pain points regarding his first installation and usage. His main concerns were (as quoted):

1. In the dependencies section, I'd be inclined to say something along the lines of "we'll show you how to use them below" because the installation docs easily lead me down a rabbit hole of checking whether the installation was working by running the commands they proposed (which didn't work because I had no clue what I was doing).

2. At the point k9s is mentioned it would be nice to have a cluster up and running, I'm not sure this is currently the case.

3. I do not understand this notation: <kbd>shift</kbd> + <kbd>f</kbd> 

4. There appears to be a missing link: "Here is a script to set the load balancer IP address tests/scripts/minikube-loadbalancer-ip.py."

5. The options passed to `qhub init` do not work

6. The default authentication seems to be via github oauth, if this is used instead it would be nice to give a warning to expect a URL that one should follow, I missed the prompt to visit GitHub developer site for a while...

7. Following the instructions (I created client id and secret key) I got the error: ValueError: Digital Ocean API requests require environment variable=DIGITALOCEAN_TOKEN defined

**Comment by laisbsc** [comment]
@leej3 Thank you so much for your solid feedback. 🥇 

I have a few questions regarding your observations, though. I will leave them here and we can make the async communication happen :)

> I will assume that points 1 to 4 refers to the [local deployment](https://cloud.qhub.dev/en/latest/source/06_developers_contrib_guide/04_tests.html?highlight=dependencies#local-testing) instructions.

1. Very valid point, indeed! I have updated the local test docs yesterday (ref. [PR](https://github.com/Quansight/qhub-cloud/blob/89908a2edc5806ef0b1e853f293f824b0e3132c5/docs/source/06_developers_contrib_guide/04_tests.md)) but will add this info to it as well.

2. We actually have this information doubled down on the docs. I have it on the Troubleshooting page as well. I reckon removing this page from the local deployment and simply adding a link to it might be a better way to add this information there.

3. This is simply a format shortcut. You can see that in GitHub it works. I've found a [script](https://github.com/github/markup/issues/497#issue-76934373) to add such a feature to Sphinx. Thanks for pointing it out as well.

4. Has been fixed on the latest PR (#441)

5. The `qhub init` command that did not work, is it [this one](https://cloud.qhub.dev/en/latest/source/06_developers_contrib_guide/04_tests.html?highlight=dependencies#deploy-qhub)? 
> `python -m qhub init local --project=thisisatest  --domain github-actions.qhub.dev --auth-provider=password --terraform-state=local`

6. Was this on the Cloud deployment? What exactly would help you with this step?

7. @aktech Can you help with this one? I am not sure what could have gone wrong.

**Comment by leej3** [comment]
This was for a local dev deployment with a minikube cluster. These are taken a little out of context. I just did a quick run through on the master branch. The docs were actually meant for the qhub version on the dev branch though... so some of these are not necessarily valid. 

Number 2. if true would be good to address. Number 7. if it can be triggered reproducibly would also be good to address: I'm not sure whether that will be true because the local minikube cluster is a slightly anomylous situation... the typical API's exposed by cloud provider's aren't available.

They read well though. A pleasing morning's read!

**Comment by laisbsc** [comment]
> This was for a local dev deployment with a minikube cluster. These are taken a little out of context. I just did a quick run through on the master branch. The docs were actually meant for the qhub version on the dev branch though... so some of these are not necessarily valid.

Alright! This is very helpful to know.

> Number 2. if true would be good to address.

I have fixed this one and currently on PR waiting for the review :) Thanks again for spotting it!

> Number 7. if it can be triggered reproducibly would also be good to address: I'm not sure whether that will be true because the local minikube cluster is a slightly anomalous situation... the typical API's exposed by cloud provider's aren't available.

I still don't really know why this happened but since it is all on the `stable` docs, it is hard to pin it down. In any case, we are preparing a demo on the different cloud providers to make sure the docs are loyal to what's required to a successful deployment. Let's see if we can nail this down :)

 
> They read well though. A pleasing morning's read!

I am very glad to hear! 🏅  Thanks again, John. I will go ahead and close this ticket. But please feel free to open one atany point and be as honest as you can about QHub. We are obsessed with feedback 📔
