### ISSUE TITLE
VS code available by default [enhancement]

### ISSUE THREAD

**Issue by leej3** [Quansight/qhub-cloud#456]
## Description
Some people like using VS code. They do not have access to VS code as part of the default deployment. We could make these people happy.

## Suggestion
We use [this project](https://github.com/dirkcgrunwald/jupyter_codeserver_proxy-). They build a wheel using make build-package, and then build a docker image and copy it inside. If I can get my hands on the Dockerfile for qhub-jupyterlab I could hack this together and submit a pull request for feedback.

## Context
I am not one of the above mentioned people but can sympathize with them and so can add this help with the addition of this feature for the sake of maximizing global utility.

**Comment by laisbsc** [comment]
This sounds quite cool! Thanks, @leej3! Let us know if there is something we can do to help with the development of that feature.

May the dev-force be with you 🎯 


> Here’s a nice write up [Quansight/aes-management#38](https://github.com/Quansight/aes-management/issues/38)

I don't have access to this repo. Hopefully someone from the team will.

**Comment by leej3** [comment]
Yes, @viniciusdc is on it. He can close this upon success and glory.

**Comment by laisbsc** [comment]
> Yes, @viniciusdc is on it. He can close this upon success and glory.

Yuhuuuul!!! He got this!

**Comment by viniciusdc** [comment]
Solved by #469

**Comment by viniciusdc** [comment]
Solved by #469
