### ISSUE TITLE
The user can access a list of other servers [bug]

### ISSUE THREAD

**Issue by leej3** [Quansight/qhub-cloud#461]
## Describe the bug

@costrouc mentioned that there doesn't seem to be a situation where we might wish the user to have access to a list of their servers or even give them the option of launching more than one jupyterlab instance. Removing this from the UI would remove all such temptation!

**Comment by danlester** [comment]
To hide the 'named servers' section, use the template vars available for ContainDS Dashboards:

https://cdsdashboards.readthedocs.io/en/stable/chapters/customization/huboptions.html
```
c.JupyterHub.template_vars = {
    'cds_hide_user_named_servers': True,
    'cds_hide_user_dashboard_servers': False
    }
```
It probably makes sense to leave the dashboard servers visible, so they can see any dashboards that are actually running.
