### ISSUE TITLE
Allow for arbitrary customization of terraform files

### ISSUE THREAD

**Issue by tylerpotts** [Quansight/qhub-cloud#58]
Currently, files need to be manually committed after running `qhub-ops` this is due to features that are not covered in the qhub configuration. We need an escape hook. This issue will require discussion on how we can achieve this.

 - [ ] Within quansight we will need to apply this solution to internal qhub clusters

**Comment by costrouc** [comment]
The use cases:
  - extra permissions to conda-store
  - integration with prefect (needs to be a feature, issue is jupyterhub api token support)
  - docker image customization (add opencv package needed), jupyterhub extension toc

We need to account for these use cases to no longer freeze it

@prasunanand @aktech and I need to have a discussion. Balance as flexible as possible and opinionated. Long term terraform tdk is the solution.

**Comment by laisbsc** [comment]
Currently, this epic is waiting on a fix for the merge conflict on issue #76.
As soon as that is done, check if the team and close the issue.

**Comment by costrouc** [comment]
Closing PR. We have talked as a team that we would like to use Terraform CDK https://github.com/Quansight/qhub-cloud/issues/327
