### ISSUE TITLE
Update Dask Dashboard Links.

### ISSUE THREAD

**Issue by dharhas** [Quansight/qhub-cloud#84]
We should update the dask config file so the dashboard link is correct. This might also fix dask-labextension.

https://jobqueue.dask.org/en/latest/interactive.html

```
Finally, you may want to update the dashboard link that is displayed in the notebook, 
shown from Cluster and Client objects. In order to do this, edit dask config file,
either ~/.config/dask/jobqueue.yaml or ~/.config/dask/distributed.yaml, and add the following:

for user launched notebooks

distributed:
  dashboard:
    link: "/proxy/{port}/status"
for JupyterHub launched notebooks

distributed:
  dashboard:
    link: "/user/{JUPYTERHUB_USER}/proxy/{port}/status"

**Comment by tylerpotts** [comment]
dask_gateway works, local clusters don't for links

Fix:
https://github.com/Quansight/qhub-terraform-modules/blob/a23f40564c602bcd70765c622b05647b281f756f/modules/kubernetes/services/meta/qhub/main.tf#L161

**Comment by laisbsc** [comment]
> Fix:
> https://github.com/Quansight/qhub-terraform-modules/blob/a23f40564c602bcd70765c622b05647b281f756f/modules/kubernetes/services/meta/qhub/main.tf#L161

Does this mean this issue has been fixed and can be closed? What's the status on this @tylerpotts?

**Comment by tylerpotts** [comment]
Haven't heard any reports of this being an issue, and it's not clear what is being asked.

Closing for now. @dharhas if you feel this needs further discussion please re-open
