### ISSUE TITLE
Kubessh integration with QHub Issues

### ISSUE THREAD

**Issue by costrouc** [Quansight/qhub-cloud#9]
Wanted to open this issue to detail the current issues with qhub integration of kubessh. I think two of the main issues revolve around.

1. qhub has introduced uid, gid, and secondary_ids with users
2.  qhub has multiple possible authentication mechanisms: quth0, github

(1) is an issue with kubessh becuase kubessh does not have the flexibily (as I know it) to customize how each kubessh pod is launched with different security contexts (e.g. uid, primary gid, secondary uids). This issue show up when trying to mount the shared filesystem of qhub since each user has a unique id causing there to be permission issues when mounting the container. The current workarround that @prasunanand and I have talked about is to simply launch all users in kubessh as root and "nicely" ask them to `su <username>` to their username. I'm guessing that we could also somehow launch jupyterlab in this manner and work around this as well.

(2) Since qhub has multiple authentication methods there is no reliable method for mapping <username> -> authentication provider id. Kubessh uses github ssh keys and (as I am aware) does not support adding arbitrary ssh public keys for each user. We need to add support in qhub for something similar to "identities" so that we can inteligently map the github username -> qhub username etc.

**Comment by tylerpotts** [comment]
Gitter conversation:
```
Rich Signell @rsignell-usgs Nov 23 06:32
@costrouc , I see that Yuvi is now working on jupyterhub-ssh instead of kubessh. Does that have any bearing here? Are you guys working together on this?

Quansight @quansightai_twitter Nov 23 08:24
[Christopher Ostrouchov, Quansight] @rsignell-usgs thank you for sharing that. IMO kubessh had some issues with requiring a seperate container to run for each user. https://github.com/yuvipanda/jupyterhub-ssh looks like the way to go and should be much easier to integrate with qhub.
[Christopher Ostrouchov, Quansight] > I switch the notebook kernel to "pangeo"
@rsignell-usgs it looks like you need to find the kernelspec name of the pangeo environment. If you are using nb_conda_envs this will be conda-pangeo I belive so you would run `jhubctl --verbose run ... --kernelspec=conda-pangeo
[Christopher Ostrouchov, Quansight] jupyterhub-ssh doesn't require the public ssh key of the user so should be much easier to add
[Christopher Ostrouchov, Quansight] which was the hard part for us to get right with kubessh
```

**Comment by laisbsc** [comment]
Hello @tylerpotts @prasunanand :)

Are there any updates on this issue? Any more details or actions after the last conversation?

**Comment by laisbsc** [comment]
After tech-discussion, this issue has been superseeded by JupyterSSH. More information on the [issue](https://github.com/yuvipanda/jupyterhub-ssh/issues/25).

**Comment by costrouc** [comment]
This issue will follow the jupyterhub-ssh issue
